#baseurl: /tufte-jekyll
title: Machine Learning and Medicine
author: Janmajay Singh
simple_search: http://google.com/search
description: By Janmajay, Researcher in Biological and Health Informatics
url: "http://janmajaysingh.github.io"
name: tufte
twitter_username: Janmajay
github_username: JanmajaySingh
markdown: kramdown
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
permalink: pretty
timezone: Asia/Tokyo
excerpt_separator: <!--more-->  # you can specify your own separator, of course.
exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'UploadToGithub.Rakefile', 'README.md']
post:
  template: _post.txt
  extension: md
page:
  template: _page.txt
  extension: md
#editor: gvim
git:
  branch: master
# transfer:
#   command: rsync
#   settings: -av
#   source: _site/
#   destination:
